name: Feature request
description: Suggest a new feature or improvement
title: "[Feature]: "
labels: ["enhancement"]
body:
  - type: markdown
    attributes:
      value: "Thanks for the suggestion! Please provide details below."
  - type: textarea
    id: problem
    attributes:
      label: Problem statement
      description: What problem are you trying to solve?
      placeholder: "As a user, I want..."
    validations:
      required: true
  - type: textarea
    id: proposal
    attributes:
      label: Proposed solution
      description: Your preferred approach or idea
      placeholder: "We could..."
    validations:
      required: true
  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives considered
      description: Any alternatives you have considered
      placeholder: "Another option is..."
    validations:
      required: false
  - type: textarea
    id: context
    attributes:
      label: Additional context
      description: Links, mockups, or background details
      placeholder: "Relevant links or screenshots"
    validations:
      required: false
